apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-compose-deployment
  namespace: mynamespace  
  labels:
    app: docker-compose
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-compose
  template:
    metadata:
      labels:
        app: docker-compose
    
    spec:
      containers:
      - name: docker-compose
        image: vinayasrri/myrepo:1.0.0
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
        ports:
        - containerPort: 80
